export const videos = [
  {
    title: 'Ló arcüregsebészet – előzetes',
    originalTitle: 'Horse Sinus Teaser',
    duration: '01:30',
    src: 'https://intissue.com/videos/animal-horse-sinus-teaser.mp4',
    poster: '/videos/posters/animal-horse-sinus-teaser.jpg',
    category: 'animal',
  },
  {
    title: 'Táti kutya története',
    originalTitle: 'TÁTI the Dog',
    duration: '01:24',
    src: 'https://intissue.com/videos/animal-t-ti-the-dog.mp4',
    poster: '/videos/posters/animal-t-ti-the-dog.jpg',
    category: 'animal',
  },
  {
    title: 'Nyíróerő okozta sérülés ellátása kutyánál II.',
    originalTitle: 'Shearing Injury Dog 2',
    duration: '00:50',
    src: 'https://intissue.com/videos/animal-management-of-shearing-injury-for-dog-2.mp4',
    poster: '/videos/posters/animal-management-of-shearing-injury-for-dog-2.jpg',
    category: 'animal',
  },
  {
    title: 'Nyíróerő okozta sérülés ellátása kutyánál',
    originalTitle: 'Shearing Injury Dog',
    duration: '00:30',
    src: 'https://intissue.com/videos/animal-management-of-shearing-injury-for-dog.mp4',
    poster: '/videos/posters/animal-management-of-shearing-injury-for-dog.jpg',
    category: 'animal',
  },
  {
    title: 'Állcsonti daganat kezelése RegBone-nal',
    originalTitle: 'Tumor Treatment with RegBone',
    duration: '00:41',
    src: 'https://intissue.com/videos/animal-new-treatment-of-tumor-for-dog-with-regbone-in-mandible.mp4',
    poster: '/videos/posters/animal-new-treatment-of-tumor-for-dog-with-regbone-in-mandible.jpg',
    category: 'animal',
  },
  {
    title: 'Dent Art',
    originalTitle: 'Dent Art',
    duration: '02:42',
    src: 'https://intissue.com/videos/surgery-dent-art.mp4',
    poster: '/videos/posters/surgery-dent-art.jpg',
    category: 'human',
  },
  {
    title: 'Parodontológia',
    originalTitle: 'Periodontology',
    duration: '00:38',
    src: 'https://intissue.com/videos/surgery-periodontology.mp4',
    poster: '/videos/posters/surgery-periodontology.jpg',
    category: 'human',
  },
  {
    title: 'Sinusemelés RegBone-nal',
    originalTitle: 'Sinus Lift with RegBone',
    duration: '02:25',
    src: 'https://intissue.com/videos/surgery-sinus-lift-with-regbone.mp4',
    poster: '/videos/posters/surgery-sinus-lift-with-regbone.jpg',
    category: 'human',
  },
  {
    title: 'A RegBone elkészítése',
    originalTitle: 'RegBone Making',
    duration: '00:58',
    src: 'https://intissue.com/videos/surgery-regbone-making.mp4',
    poster: '/videos/posters/surgery-regbone-making.jpg',
    category: 'human',
  },
  {
    title: 'Epulis kezelése RegBone-nal',
    originalTitle: 'Epulis with RegBone',
    duration: '00:25',
    src: 'https://intissue.com/videos/surgery-new-management-of-epulis-with-regbone.mp4',
    poster: '/videos/posters/surgery-new-management-of-epulis-with-regbone.jpg',
    category: 'human',
  },
  {
    title: 'Periimplantitis kezelése',
    originalTitle: 'Peri Implantitis',
    duration: '01:17',
    src: 'https://intissue.com/videos/surgery-management-of-peri-implantitis.mp4',
    poster: '/videos/posters/surgery-management-of-peri-implantitis.jpg',
    category: 'human',
  },
  {
    title: 'Vertikális és horizontális augmentáció',
    originalTitle: 'Vertical & Horizontal Augmentation',
    duration: '00:40',
    src: 'https://intissue.com/videos/surgery-vertical-and-horizontal-augmentation.mp4',
    poster: '/videos/posters/surgery-vertical-and-horizontal-augmentation.jpg',
    category: 'human',
  },
  {
    title: 'Fogeltávolítás, azonnali GBR – RegBone3',
    originalTitle: 'Extractio, Sofort GBR with RegBone3',
    duration: '01:05',
    src: 'https://intissue.com/videos/surgery-extractio-sofort-gbr-with-regbone3.mp4',
    poster: '/videos/posters/surgery-extractio-sofort-gbr-with-regbone3.jpg',
    category: 'human',
  },
  {
    title: 'Sinusemelés laterális feltárásból – RegBone2',
    originalTitle: 'Sinus Lift - Lateral Approach with RegBone2',
    duration: '01:42',
    src: 'https://intissue.com/videos/surgery-sinus-lift-lateral-approach-with-regbone2.mp4',
    poster: '/videos/posters/surgery-sinus-lift-lateral-approach-with-regbone2.jpg',
    category: 'human',
  },
  {
    title: 'Parodontológiai eset',
    originalTitle: 'Paradontology',
    duration: '01:05',
    src: 'https://intissue.com/videos/surgery-paradontology.mp4',
    poster: '/videos/posters/surgery-paradontology.jpg',
    category: 'human',
  },
  {
    title: 'Augmentáció 3D titánhálóval',
    originalTitle: 'Augmentation with 3D Titan Mesh',
    duration: '00:40',
    src: 'https://intissue.com/videos/surgery-vertical-and-horizontal-augmentation-with-3d-titan-mesh.mp4',
    poster: '/videos/posters/surgery-vertical-and-horizontal-augmentation-with-3d-titan-mesh.jpg',
    category: 'human',
  },
];
